### https://dummyapi.io/docs/user

### GET request with a header (all users)
GET https://dummyapi.io/data/v1/user
Accept: application/json
app-id: 6318370b8733824e8402f913

### GET specific user
GET https://dummyapi.io/data/v1/user/6318573a531c340da33823d7
Accept: application/json
app-id: 6318370b8733824e8402f913

### POST new user
POST https://dummyapi.io/data/v1/user/create
Content-Type: application/json
app-id: 6318370b8733824e8402f913

{
  "title": "mr",
  "firstName": "Joerg",
  "lastName": "Oertel",
  "picture": "https://randomuser.me/api/portraits/man/58.jpg",
  "gender": "male",
  "email": "joerg@joerg.dk",
  "dateOfBirth": "1970-04-30T19:26:49.610Z",
  "phone": "34554334",
  "location": {
    "street": "strøget",
    "city": "Lyngby",
    "state": "København",
    "country": "Denmark",
    "timezone": "0:00"
  }
}

### Update new user
PUT https://dummyapi.io/data/v1/user/6318573a531c340da33823d7
Content-Type: application/json
app-id: 6318370b8733824e8402f913

{
  "location": {
    "street": "strøget",
    "city": "Lyngby",
    "state": "Rønne",
    "country": "Denmark",
    "timezone": "0:00",
    "test": "test"
  }

}

### Delete user
DELETE https://dummyapi.io/data/v1/user/6318370b8733824e8402f913
Content-Type: application/json
app-id: 6318573a531c340da33823d7



